graph TD
  image["placeholder\nimage"]
  valid_mask["placeholder\nvalid_mask"]
  station_id["placeholder\nstation_id"]
  geometry_id["placeholder\ngeometry_id"]
  model_conditioner_station_embedding["call_module\nmodel.conditioner.station_embedding"]
  model_conditioner_geometry_embedding["call_module\nmodel.conditioner.geometry_embedding"]
  add["call_function\n<built-in function add>"]
  model_conditioner_proj_0["call_module\nmodel.conditioner.proj.0"]
  model_conditioner_proj_1["call_module\nmodel.conditioner.proj.1"]
  model_conditioner_proj_2["call_module\nmodel.conditioner.proj.2"]
  model_conditioner_proj_3["call_module\nmodel.conditioner.proj.3"]
  model_stem_0_block_0["call_module\nmodel.stem.0.block.0"]
  model_stem_0_block_1["call_module\nmodel.stem.0.block.1"]
  model_stem_0_block_2["call_module\nmodel.stem.0.block.2"]
  model_stem_1_block_0["call_module\nmodel.stem.1.block.0"]
  model_stem_1_block_1["call_module\nmodel.stem.1.block.1"]
  model_stem_1_block_2["call_module\nmodel.stem.1.block.2"]
  model_stem_affine_scale["call_module\nmodel.stem_affine.scale"]
  tanh["call_function\n<built-in method tanh of type object at 0x00007FF812C1EE90>"]
  unsqueeze["call_method\nunsqueeze"]
  unsqueeze_1["call_method\nunsqueeze"]
  model_stem_affine_bias["call_module\nmodel.stem_affine.bias"]
  unsqueeze_2["call_method\nunsqueeze"]
  unsqueeze_3["call_method\nunsqueeze"]
  add_1["call_function\n<built-in function add>"]
  mul["call_function\n<built-in function mul>"]
  add_2["call_function\n<built-in function add>"]
  model_stage1_proj["call_module\nmodel.stage1_proj"]
  model_stage1_0_depthwise["call_module\nmodel.stage1.0.depthwise"]
  permute["call_method\npermute"]
  getattr_1["call_function\n<built-in function getattr>"]
  getitem["call_function\n<built-in function getitem>"]
  model_stage1_0_norm_weight["get_attr\nmodel.stage1.0.norm.weight"]
  model_stage1_0_norm_bias["get_attr\nmodel.stage1.0.norm.bias"]
  layer_norm["call_function\n<function layer_norm at 0x000001AD0D86BE50>"]
  permute_1["call_method\npermute"]
  model_stage1_0_pointwise_0["call_module\nmodel.stage1.0.pointwise.0"]
  model_stage1_0_pointwise_1["call_module\nmodel.stage1.0.pointwise.1"]
  model_stage1_0_pointwise_2["call_module\nmodel.stage1.0.pointwise.2"]
  model_stage1_0_scale["get_attr\nmodel.stage1.0.scale"]
  view["call_method\nview"]
  mul_1["call_function\n<built-in function mul>"]
  add_3["call_function\n<built-in function add>"]
  model_stage1_1_depthwise["call_module\nmodel.stage1.1.depthwise"]
  permute_2["call_method\npermute"]
  getattr_2["call_function\n<built-in function getattr>"]
  getitem_1["call_function\n<built-in function getitem>"]
  model_stage1_1_norm_weight["get_attr\nmodel.stage1.1.norm.weight"]
  model_stage1_1_norm_bias["get_attr\nmodel.stage1.1.norm.bias"]
  layer_norm_1["call_function\n<function layer_norm at 0x000001AD0D86BE50>"]
  permute_3["call_method\npermute"]
  model_stage1_1_pointwise_0["call_module\nmodel.stage1.1.pointwise.0"]
  model_stage1_1_pointwise_1["call_module\nmodel.stage1.1.pointwise.1"]
  model_stage1_1_pointwise_2["call_module\nmodel.stage1.1.pointwise.2"]
  model_stage1_1_scale["get_attr\nmodel.stage1.1.scale"]
  view_1["call_method\nview"]
  mul_2["call_function\n<built-in function mul>"]
  add_4["call_function\n<built-in function add>"]
  model_stage1_affine_scale["call_module\nmodel.stage1_affine.scale"]
  tanh_1["call_function\n<built-in method tanh of type object at 0x00007FF812C1EE90>"]
  unsqueeze_4["call_method\nunsqueeze"]
  unsqueeze_5["call_method\nunsqueeze"]
  model_stage1_affine_bias["call_module\nmodel.stage1_affine.bias"]
  unsqueeze_6["call_method\nunsqueeze"]
  unsqueeze_7["call_method\nunsqueeze"]
  add_5["call_function\n<built-in function add>"]
  mul_3["call_function\n<built-in function mul>"]
  add_6["call_function\n<built-in function add>"]
  permute_4["call_method\npermute"]
  getattr_3["call_function\n<built-in function getattr>"]
  getitem_2["call_function\n<built-in function getitem>"]
  model_stage2_down_block_0_weight["get_attr\nmodel.stage2_down.block.0.weight"]
  model_stage2_down_block_0_bias["get_attr\nmodel.stage2_down.block.0.bias"]
  layer_norm_2["call_function\n<function layer_norm at 0x000001AD0D86BE50>"]
  permute_5["call_method\npermute"]
  model_stage2_down_block_1["call_module\nmodel.stage2_down.block.1"]
  model_stage2_0_depthwise["call_module\nmodel.stage2.0.depthwise"]
  permute_6["call_method\npermute"]
  getattr_4["call_function\n<built-in function getattr>"]
  getitem_3["call_function\n<built-in function getitem>"]
  model_stage2_0_norm_weight["get_attr\nmodel.stage2.0.norm.weight"]
  model_stage2_0_norm_bias["get_attr\nmodel.stage2.0.norm.bias"]
  layer_norm_3["call_function\n<function layer_norm at 0x000001AD0D86BE50>"]
  permute_7["call_method\npermute"]
  model_stage2_0_pointwise_0["call_module\nmodel.stage2.0.pointwise.0"]
  model_stage2_0_pointwise_1["call_module\nmodel.stage2.0.pointwise.1"]
  model_stage2_0_pointwise_2["call_module\nmodel.stage2.0.pointwise.2"]
  model_stage2_0_scale["get_attr\nmodel.stage2.0.scale"]
  view_2["call_method\nview"]
  mul_4["call_function\n<built-in function mul>"]
  add_7["call_function\n<built-in function add>"]
  model_stage2_1_depthwise["call_module\nmodel.stage2.1.depthwise"]
  permute_8["call_method\npermute"]
  getattr_5["call_function\n<built-in function getattr>"]
  getitem_4["call_function\n<built-in function getitem>"]
  model_stage2_1_norm_weight["get_attr\nmodel.stage2.1.norm.weight"]
  model_stage2_1_norm_bias["get_attr\nmodel.stage2.1.norm.bias"]
  layer_norm_4["call_function\n<function layer_norm at 0x000001AD0D86BE50>"]
  permute_9["call_method\npermute"]
  model_stage2_1_pointwise_0["call_module\nmodel.stage2.1.pointwise.0"]
  model_stage2_1_pointwise_1["call_module\nmodel.stage2.1.pointwise.1"]
  model_stage2_1_pointwise_2["call_module\nmodel.stage2.1.pointwise.2"]
  model_stage2_1_scale["get_attr\nmodel.stage2.1.scale"]
  view_3["call_method\nview"]
  mul_5["call_function\n<built-in function mul>"]
  add_8["call_function\n<built-in function add>"]
  model_stage2_affine_scale["call_module\nmodel.stage2_affine.scale"]
  tanh_2["call_function\n<built-in method tanh of type object at 0x00007FF812C1EE90>"]
  unsqueeze_8["call_method\nunsqueeze"]
  unsqueeze_9["call_method\nunsqueeze"]
  model_stage2_affine_bias["call_module\nmodel.stage2_affine.bias"]
  unsqueeze_10["call_method\nunsqueeze"]
  unsqueeze_11["call_method\nunsqueeze"]
  add_9["call_function\n<built-in function add>"]
  mul_6["call_function\n<built-in function mul>"]
  add_10["call_function\n<built-in function add>"]
  permute_10["call_method\npermute"]
  getattr_6["call_function\n<built-in function getattr>"]
  getitem_5["call_function\n<built-in function getitem>"]
  model_stage3_down_block_0_weight["get_attr\nmodel.stage3_down.block.0.weight"]
  model_stage3_down_block_0_bias["get_attr\nmodel.stage3_down.block.0.bias"]
  layer_norm_5["call_function\n<function layer_norm at 0x000001AD0D86BE50>"]
  permute_11["call_method\npermute"]
  model_stage3_down_block_1["call_module\nmodel.stage3_down.block.1"]
  model_stage3_0_depthwise["call_module\nmodel.stage3.0.depthwise"]
  permute_12["call_method\npermute"]
  getattr_7["call_function\n<built-in function getattr>"]
  getitem_6["call_function\n<built-in function getitem>"]
  model_stage3_0_norm_weight["get_attr\nmodel.stage3.0.norm.weight"]
  model_stage3_0_norm_bias["get_attr\nmodel.stage3.0.norm.bias"]
  layer_norm_6["call_function\n<function layer_norm at 0x000001AD0D86BE50>"]
  permute_13["call_method\npermute"]
  model_stage3_0_pointwise_0["call_module\nmodel.stage3.0.pointwise.0"]
  model_stage3_0_pointwise_1["call_module\nmodel.stage3.0.pointwise.1"]
  model_stage3_0_pointwise_2["call_module\nmodel.stage3.0.pointwise.2"]
  model_stage3_0_scale["get_attr\nmodel.stage3.0.scale"]
  view_4["call_method\nview"]
  mul_7["call_function\n<built-in function mul>"]
  add_11["call_function\n<built-in function add>"]
  model_stage3_1_depthwise["call_module\nmodel.stage3.1.depthwise"]
  permute_14["call_method\npermute"]
  getattr_8["call_function\n<built-in function getattr>"]
  getitem_7["call_function\n<built-in function getitem>"]
  model_stage3_1_norm_weight["get_attr\nmodel.stage3.1.norm.weight"]
  model_stage3_1_norm_bias["get_attr\nmodel.stage3.1.norm.bias"]
  layer_norm_7["call_function\n<function layer_norm at 0x000001AD0D86BE50>"]
  permute_15["call_method\npermute"]
  model_stage3_1_pointwise_0["call_module\nmodel.stage3.1.pointwise.0"]
  model_stage3_1_pointwise_1["call_module\nmodel.stage3.1.pointwise.1"]
  model_stage3_1_pointwise_2["call_module\nmodel.stage3.1.pointwise.2"]
  model_stage3_1_scale["get_attr\nmodel.stage3.1.scale"]
  view_5["call_method\nview"]
  mul_8["call_function\n<built-in function mul>"]
  add_12["call_function\n<built-in function add>"]
  model_stage3_2_depthwise["call_module\nmodel.stage3.2.depthwise"]
  permute_16["call_method\npermute"]
  getattr_9["call_function\n<built-in function getattr>"]
  getitem_8["call_function\n<built-in function getitem>"]
  model_stage3_2_norm_weight["get_attr\nmodel.stage3.2.norm.weight"]
  model_stage3_2_norm_bias["get_attr\nmodel.stage3.2.norm.bias"]
  layer_norm_8["call_function\n<function layer_norm at 0x000001AD0D86BE50>"]
  permute_17["call_method\npermute"]
  model_stage3_2_pointwise_0["call_module\nmodel.stage3.2.pointwise.0"]
  model_stage3_2_pointwise_1["call_module\nmodel.stage3.2.pointwise.1"]
  model_stage3_2_pointwise_2["call_module\nmodel.stage3.2.pointwise.2"]
  model_stage3_2_scale["get_attr\nmodel.stage3.2.scale"]
  view_6["call_method\nview"]
  mul_9["call_function\n<built-in function mul>"]
  add_13["call_function\n<built-in function add>"]
  model_stage3_3_depthwise["call_module\nmodel.stage3.3.depthwise"]
  permute_18["call_method\npermute"]
  getattr_10["call_function\n<built-in function getattr>"]
  getitem_9["call_function\n<built-in function getitem>"]
  model_stage3_3_norm_weight["get_attr\nmodel.stage3.3.norm.weight"]
  model_stage3_3_norm_bias["get_attr\nmodel.stage3.3.norm.bias"]
  layer_norm_9["call_function\n<function layer_norm at 0x000001AD0D86BE50>"]
  permute_19["call_method\npermute"]
  model_stage3_3_pointwise_0["call_module\nmodel.stage3.3.pointwise.0"]
  model_stage3_3_pointwise_1["call_module\nmodel.stage3.3.pointwise.1"]
  model_stage3_3_pointwise_2["call_module\nmodel.stage3.3.pointwise.2"]
  model_stage3_3_scale["get_attr\nmodel.stage3.3.scale"]
  view_7["call_method\nview"]
  mul_10["call_function\n<built-in function mul>"]
  add_14["call_function\n<built-in function add>"]
  model_stage3_affine_scale["call_module\nmodel.stage3_affine.scale"]
  tanh_3["call_function\n<built-in method tanh of type object at 0x00007FF812C1EE90>"]
  unsqueeze_12["call_method\nunsqueeze"]
  unsqueeze_13["call_method\nunsqueeze"]
  model_stage3_affine_bias["call_module\nmodel.stage3_affine.bias"]
  unsqueeze_14["call_method\nunsqueeze"]
  unsqueeze_15["call_method\nunsqueeze"]
  add_15["call_function\n<built-in function add>"]
  mul_11["call_function\n<built-in function mul>"]
  add_16["call_function\n<built-in function add>"]
  permute_20["call_method\npermute"]
  getattr_11["call_function\n<built-in function getattr>"]
  getitem_10["call_function\n<built-in function getitem>"]
  model_stage4_down_block_0_weight["get_attr\nmodel.stage4_down.block.0.weight"]
  model_stage4_down_block_0_bias["get_attr\nmodel.stage4_down.block.0.bias"]
  layer_norm_10["call_function\n<function layer_norm at 0x000001AD0D86BE50>"]
  permute_21["call_method\npermute"]
  model_stage4_down_block_1["call_module\nmodel.stage4_down.block.1"]
  model_stage4_0_depthwise["call_module\nmodel.stage4.0.depthwise"]
  permute_22["call_method\npermute"]
  getattr_12["call_function\n<built-in function getattr>"]
  getitem_11["call_function\n<built-in function getitem>"]
  model_stage4_0_norm_weight["get_attr\nmodel.stage4.0.norm.weight"]
  model_stage4_0_norm_bias["get_attr\nmodel.stage4.0.norm.bias"]
  layer_norm_11["call_function\n<function layer_norm at 0x000001AD0D86BE50>"]
  permute_23["call_method\npermute"]
  model_stage4_0_pointwise_0["call_module\nmodel.stage4.0.pointwise.0"]
  model_stage4_0_pointwise_1["call_module\nmodel.stage4.0.pointwise.1"]
  model_stage4_0_pointwise_2["call_module\nmodel.stage4.0.pointwise.2"]
  model_stage4_0_scale["get_attr\nmodel.stage4.0.scale"]
  view_8["call_method\nview"]
  mul_12["call_function\n<built-in function mul>"]
  add_17["call_function\n<built-in function add>"]
  model_stage4_1_depthwise["call_module\nmodel.stage4.1.depthwise"]
  permute_24["call_method\npermute"]
  getattr_13["call_function\n<built-in function getattr>"]
  getitem_12["call_function\n<built-in function getitem>"]
  model_stage4_1_norm_weight["get_attr\nmodel.stage4.1.norm.weight"]
  model_stage4_1_norm_bias["get_attr\nmodel.stage4.1.norm.bias"]
  layer_norm_12["call_function\n<function layer_norm at 0x000001AD0D86BE50>"]
  permute_25["call_method\npermute"]
  model_stage4_1_pointwise_0["call_module\nmodel.stage4.1.pointwise.0"]
  model_stage4_1_pointwise_1["call_module\nmodel.stage4.1.pointwise.1"]
  model_stage4_1_pointwise_2["call_module\nmodel.stage4.1.pointwise.2"]
  model_stage4_1_scale["get_attr\nmodel.stage4.1.scale"]
  view_9["call_method\nview"]
  mul_13["call_function\n<built-in function mul>"]
  add_18["call_function\n<built-in function add>"]
  model_stage4_affine_scale["call_module\nmodel.stage4_affine.scale"]
  tanh_4["call_function\n<built-in method tanh of type object at 0x00007FF812C1EE90>"]
  unsqueeze_16["call_method\nunsqueeze"]
  unsqueeze_17["call_method\nunsqueeze"]
  model_stage4_affine_bias["call_module\nmodel.stage4_affine.bias"]
  unsqueeze_18["call_method\nunsqueeze"]
  unsqueeze_19["call_method\nunsqueeze"]
  add_19["call_function\n<built-in function add>"]
  mul_14["call_function\n<built-in function mul>"]
  add_20["call_function\n<built-in function add>"]
  model_pyramid_laterals_0["call_module\nmodel.pyramid_laterals.0"]
  model_pyramid_laterals_1["call_module\nmodel.pyramid_laterals.1"]
  model_pyramid_laterals_2["call_module\nmodel.pyramid_laterals.2"]
  model_pyramid_laterals_3["call_module\nmodel.pyramid_laterals.3"]
  getattr_14["call_function\n<built-in function getattr>"]
  getitem_13["call_function\n<built-in function getitem>"]
  interpolate["call_function\n<function interpolate at 0x000001AD0D8E8790>"]
  model_bifpn_0_td3_weights["get_attr\nmodel.bifpn.0.td3.weights"]
  relu["call_function\n<function relu at 0x000001AD0D869DC0>"]
  sum_1["call_method\nsum"]
  clamp_min["call_method\nclamp_min"]
  truediv["call_function\n<built-in function truediv>"]
  stack["call_function\n<built-in method stack of type object at 0x00007FF812C1EE90>"]
  view_10["call_method\nview"]
  mul_15["call_function\n<built-in function mul>"]
  sum_2["call_method\nsum"]
  model_bifpn_0_td3_refine_0["call_module\nmodel.bifpn.0.td3.refine.0"]
  model_bifpn_0_td3_refine_1["call_module\nmodel.bifpn.0.td3.refine.1"]
  model_bifpn_0_td3_refine_2["call_module\nmodel.bifpn.0.td3.refine.2"]
  model_bifpn_0_td3_refine_3["call_module\nmodel.bifpn.0.td3.refine.3"]
  getattr_15["call_function\n<built-in function getattr>"]
  getitem_14["call_function\n<built-in function getitem>"]
  interpolate_1["call_function\n<function interpolate at 0x000001AD0D8E8790>"]
  model_bifpn_0_td2_weights["get_attr\nmodel.bifpn.0.td2.weights"]
  relu_1["call_function\n<function relu at 0x000001AD0D869DC0>"]
  sum_3["call_method\nsum"]
  clamp_min_1["call_method\nclamp_min"]
  truediv_1["call_function\n<built-in function truediv>"]
  stack_1["call_function\n<built-in method stack of type object at 0x00007FF812C1EE90>"]
  view_11["call_method\nview"]
  mul_16["call_function\n<built-in function mul>"]
  sum_4["call_method\nsum"]
  model_bifpn_0_td2_refine_0["call_module\nmodel.bifpn.0.td2.refine.0"]
  model_bifpn_0_td2_refine_1["call_module\nmodel.bifpn.0.td2.refine.1"]
  model_bifpn_0_td2_refine_2["call_module\nmodel.bifpn.0.td2.refine.2"]
  model_bifpn_0_td2_refine_3["call_module\nmodel.bifpn.0.td2.refine.3"]
  getattr_16["call_function\n<built-in function getattr>"]
  getitem_15["call_function\n<built-in function getitem>"]
  interpolate_2["call_function\n<function interpolate at 0x000001AD0D8E8790>"]
  model_bifpn_0_td1_weights["get_attr\nmodel.bifpn.0.td1.weights"]
  relu_2["call_function\n<function relu at 0x000001AD0D869DC0>"]
  sum_5["call_method\nsum"]
  clamp_min_2["call_method\nclamp_min"]
  truediv_2["call_function\n<built-in function truediv>"]
  stack_2["call_function\n<built-in method stack of type object at 0x00007FF812C1EE90>"]
  view_12["call_method\nview"]
  mul_17["call_function\n<built-in function mul>"]
  sum_6["call_method\nsum"]
  model_bifpn_0_td1_refine_0["call_module\nmodel.bifpn.0.td1.refine.0"]
  model_bifpn_0_td1_refine_1["call_module\nmodel.bifpn.0.td1.refine.1"]
  model_bifpn_0_td1_refine_2["call_module\nmodel.bifpn.0.td1.refine.2"]
  model_bifpn_0_td1_refine_3["call_module\nmodel.bifpn.0.td1.refine.3"]
  getattr_17["call_function\n<built-in function getattr>"]
  getitem_16["call_function\n<built-in function getitem>"]
  adaptive_max_pool2d["call_function\n<function boolean_dispatch.<locals>.fn at 0x000001AD0D869670>"]
  model_bifpn_0_out2_weights["get_attr\nmodel.bifpn.0.out2.weights"]
  relu_3["call_function\n<function relu at 0x000001AD0D869DC0>"]
  sum_7["call_method\nsum"]
  clamp_min_3["call_method\nclamp_min"]
  truediv_3["call_function\n<built-in function truediv>"]
  stack_3["call_function\n<built-in method stack of type object at 0x00007FF812C1EE90>"]
  view_13["call_method\nview"]
  mul_18["call_function\n<built-in function mul>"]
  sum_8["call_method\nsum"]
  model_bifpn_0_out2_refine_0["call_module\nmodel.bifpn.0.out2.refine.0"]
  model_bifpn_0_out2_refine_1["call_module\nmodel.bifpn.0.out2.refine.1"]
  model_bifpn_0_out2_refine_2["call_module\nmodel.bifpn.0.out2.refine.2"]
  model_bifpn_0_out2_refine_3["call_module\nmodel.bifpn.0.out2.refine.3"]
  getattr_18["call_function\n<built-in function getattr>"]
  getitem_17["call_function\n<built-in function getitem>"]
  adaptive_max_pool2d_1["call_function\n<function boolean_dispatch.<locals>.fn at 0x000001AD0D869670>"]
  model_bifpn_0_out3_weights["get_attr\nmodel.bifpn.0.out3.weights"]
  relu_4["call_function\n<function relu at 0x000001AD0D869DC0>"]
  sum_9["call_method\nsum"]
  clamp_min_4["call_method\nclamp_min"]
  truediv_4["call_function\n<built-in function truediv>"]
  stack_4["call_function\n<built-in method stack of type object at 0x00007FF812C1EE90>"]
  view_14["call_method\nview"]
  mul_19["call_function\n<built-in function mul>"]
  sum_10["call_method\nsum"]
  model_bifpn_0_out3_refine_0["call_module\nmodel.bifpn.0.out3.refine.0"]
  model_bifpn_0_out3_refine_1["call_module\nmodel.bifpn.0.out3.refine.1"]
  model_bifpn_0_out3_refine_2["call_module\nmodel.bifpn.0.out3.refine.2"]
  model_bifpn_0_out3_refine_3["call_module\nmodel.bifpn.0.out3.refine.3"]
  getattr_19["call_function\n<built-in function getattr>"]
  getitem_18["call_function\n<built-in function getitem>"]
  adaptive_max_pool2d_2["call_function\n<function boolean_dispatch.<locals>.fn at 0x000001AD0D869670>"]
  model_bifpn_0_out4_weights["get_attr\nmodel.bifpn.0.out4.weights"]
  relu_5["call_function\n<function relu at 0x000001AD0D869DC0>"]
  sum_11["call_method\nsum"]
  clamp_min_5["call_method\nclamp_min"]
  truediv_5["call_function\n<built-in function truediv>"]
  stack_5["call_function\n<built-in method stack of type object at 0x00007FF812C1EE90>"]
  view_15["call_method\nview"]
  mul_20["call_function\n<built-in function mul>"]
  sum_12["call_method\nsum"]
  model_bifpn_0_out4_refine_0["call_module\nmodel.bifpn.0.out4.refine.0"]
  model_bifpn_0_out4_refine_1["call_module\nmodel.bifpn.0.out4.refine.1"]
  model_bifpn_0_out4_refine_2["call_module\nmodel.bifpn.0.out4.refine.2"]
  model_bifpn_0_out4_refine_3["call_module\nmodel.bifpn.0.out4.refine.3"]
  getattr_20["call_function\n<built-in function getattr>"]
  getitem_19["call_function\n<built-in function getitem>"]
  interpolate_3["call_function\n<function interpolate at 0x000001AD0D8E8790>"]
  model_bifpn_1_td3_weights["get_attr\nmodel.bifpn.1.td3.weights"]
  relu_6["call_function\n<function relu at 0x000001AD0D869DC0>"]
  sum_13["call_method\nsum"]
  clamp_min_6["call_method\nclamp_min"]
  truediv_6["call_function\n<built-in function truediv>"]
  stack_6["call_function\n<built-in method stack of type object at 0x00007FF812C1EE90>"]
  view_16["call_method\nview"]
  mul_21["call_function\n<built-in function mul>"]
  sum_14["call_method\nsum"]
  model_bifpn_1_td3_refine_0["call_module\nmodel.bifpn.1.td3.refine.0"]
  model_bifpn_1_td3_refine_1["call_module\nmodel.bifpn.1.td3.refine.1"]
  model_bifpn_1_td3_refine_2["call_module\nmodel.bifpn.1.td3.refine.2"]
  model_bifpn_1_td3_refine_3["call_module\nmodel.bifpn.1.td3.refine.3"]
  getattr_21["call_function\n<built-in function getattr>"]
  getitem_20["call_function\n<built-in function getitem>"]
  interpolate_4["call_function\n<function interpolate at 0x000001AD0D8E8790>"]
  model_bifpn_1_td2_weights["get_attr\nmodel.bifpn.1.td2.weights"]
  relu_7["call_function\n<function relu at 0x000001AD0D869DC0>"]
  sum_15["call_method\nsum"]
  clamp_min_7["call_method\nclamp_min"]
  truediv_7["call_function\n<built-in function truediv>"]
  stack_7["call_function\n<built-in method stack of type object at 0x00007FF812C1EE90>"]
  view_17["call_method\nview"]
  mul_22["call_function\n<built-in function mul>"]
  sum_16["call_method\nsum"]
  model_bifpn_1_td2_refine_0["call_module\nmodel.bifpn.1.td2.refine.0"]
  model_bifpn_1_td2_refine_1["call_module\nmodel.bifpn.1.td2.refine.1"]
  model_bifpn_1_td2_refine_2["call_module\nmodel.bifpn.1.td2.refine.2"]
  model_bifpn_1_td2_refine_3["call_module\nmodel.bifpn.1.td2.refine.3"]
  getattr_22["call_function\n<built-in function getattr>"]
  getitem_21["call_function\n<built-in function getitem>"]
  interpolate_5["call_function\n<function interpolate at 0x000001AD0D8E8790>"]
  model_bifpn_1_td1_weights["get_attr\nmodel.bifpn.1.td1.weights"]
  relu_8["call_function\n<function relu at 0x000001AD0D869DC0>"]
  sum_17["call_method\nsum"]
  clamp_min_8["call_method\nclamp_min"]
  truediv_8["call_function\n<built-in function truediv>"]
  stack_8["call_function\n<built-in method stack of type object at 0x00007FF812C1EE90>"]
  view_18["call_method\nview"]
  mul_23["call_function\n<built-in function mul>"]
  sum_18["call_method\nsum"]
  model_bifpn_1_td1_refine_0["call_module\nmodel.bifpn.1.td1.refine.0"]
  model_bifpn_1_td1_refine_1["call_module\nmodel.bifpn.1.td1.refine.1"]
  model_bifpn_1_td1_refine_2["call_module\nmodel.bifpn.1.td1.refine.2"]
  model_bifpn_1_td1_refine_3["call_module\nmodel.bifpn.1.td1.refine.3"]
  getattr_23["call_function\n<built-in function getattr>"]
  getitem_22["call_function\n<built-in function getitem>"]
  adaptive_max_pool2d_3["call_function\n<function boolean_dispatch.<locals>.fn at 0x000001AD0D869670>"]
  model_bifpn_1_out2_weights["get_attr\nmodel.bifpn.1.out2.weights"]
  relu_9["call_function\n<function relu at 0x000001AD0D869DC0>"]
  sum_19["call_method\nsum"]
  clamp_min_9["call_method\nclamp_min"]
  truediv_9["call_function\n<built-in function truediv>"]
  stack_9["call_function\n<built-in method stack of type object at 0x00007FF812C1EE90>"]
  view_19["call_method\nview"]
  mul_24["call_function\n<built-in function mul>"]
  sum_20["call_method\nsum"]
  model_bifpn_1_out2_refine_0["call_module\nmodel.bifpn.1.out2.refine.0"]
  model_bifpn_1_out2_refine_1["call_module\nmodel.bifpn.1.out2.refine.1"]
  model_bifpn_1_out2_refine_2["call_module\nmodel.bifpn.1.out2.refine.2"]
  model_bifpn_1_out2_refine_3["call_module\nmodel.bifpn.1.out2.refine.3"]
  getattr_24["call_function\n<built-in function getattr>"]
  getitem_23["call_function\n<built-in function getitem>"]
  adaptive_max_pool2d_4["call_function\n<function boolean_dispatch.<locals>.fn at 0x000001AD0D869670>"]
  model_bifpn_1_out3_weights["get_attr\nmodel.bifpn.1.out3.weights"]
  relu_10["call_function\n<function relu at 0x000001AD0D869DC0>"]
  sum_21["call_method\nsum"]
  clamp_min_10["call_method\nclamp_min"]
  truediv_10["call_function\n<built-in function truediv>"]
  stack_10["call_function\n<built-in method stack of type object at 0x00007FF812C1EE90>"]
  view_20["call_method\nview"]
  mul_25["call_function\n<built-in function mul>"]
  sum_22["call_method\nsum"]
  model_bifpn_1_out3_refine_0["call_module\nmodel.bifpn.1.out3.refine.0"]
  model_bifpn_1_out3_refine_1["call_module\nmodel.bifpn.1.out3.refine.1"]
  model_bifpn_1_out3_refine_2["call_module\nmodel.bifpn.1.out3.refine.2"]
  model_bifpn_1_out3_refine_3["call_module\nmodel.bifpn.1.out3.refine.3"]
  getattr_25["call_function\n<built-in function getattr>"]
  getitem_24["call_function\n<built-in function getitem>"]
  adaptive_max_pool2d_5["call_function\n<function boolean_dispatch.<locals>.fn at 0x000001AD0D869670>"]
  model_bifpn_1_out4_weights["get_attr\nmodel.bifpn.1.out4.weights"]
  relu_11["call_function\n<function relu at 0x000001AD0D869DC0>"]
  sum_23["call_method\nsum"]
  clamp_min_11["call_method\nclamp_min"]
  truediv_11["call_function\n<built-in function truediv>"]
  stack_11["call_function\n<built-in method stack of type object at 0x00007FF812C1EE90>"]
  view_21["call_method\nview"]
  mul_26["call_function\n<built-in function mul>"]
  sum_24["call_method\nsum"]
  model_bifpn_1_out4_refine_0["call_module\nmodel.bifpn.1.out4.refine.0"]
  model_bifpn_1_out4_refine_1["call_module\nmodel.bifpn.1.out4.refine.1"]
  model_bifpn_1_out4_refine_2["call_module\nmodel.bifpn.1.out4.refine.2"]
  model_bifpn_1_out4_refine_3["call_module\nmodel.bifpn.1.out4.refine.3"]
  getattr_26["call_function\n<built-in function getattr>"]
  getitem_25["call_function\n<built-in function getitem>"]
  interpolate_6["call_function\n<function interpolate at 0x000001AD0D8E8790>"]
  adaptive_avg_pool2d["call_function\n<function adaptive_avg_pool2d at 0x000001AD0D8698B0>"]
  adaptive_max_pool2d_6["call_function\n<function boolean_dispatch.<locals>.fn at 0x000001AD0D869670>"]
  model_global_context_project["call_module\nmodel.global_context_project"]
  mul_27["call_function\n<built-in function mul>"]
  mul_28["call_function\n<built-in function mul>"]
  sum_25["call_method\nsum"]
  clamp_min_12["call_method\nclamp_min"]
  sum_26["call_method\nsum"]
  truediv_12["call_function\n<built-in function truediv>"]
  model_global_project["call_module\nmodel.global_project"]
  getitem_26["call_function\n<built-in function getitem>"]
  getitem_27["call_function\n<built-in function getitem>"]
  getitem_28["call_function\n<built-in function getitem>"]
  getitem_29["call_function\n<built-in function getitem>"]
  getitem_30["call_function\n<built-in function getitem>"]
  getitem_31["call_function\n<built-in function getitem>"]
  getitem_32["call_function\n<built-in function getitem>"]
  getitem_33["call_function\n<built-in function getitem>"]
  getitem_34["call_function\n<built-in function getitem>"]
  getitem_35["call_function\n<built-in function getitem>"]
  getitem_36["call_function\n<built-in function getitem>"]
  getitem_37["call_function\n<built-in function getitem>"]
  getitem_38["call_function\n<built-in function getitem>"]
  getitem_39["call_function\n<built-in function getitem>"]
  getitem_40["call_function\n<built-in function getitem>"]
  getitem_41["call_function\n<built-in function getitem>"]
  getitem_42["call_function\n<built-in function getitem>"]
  getitem_43["call_function\n<built-in function getitem>"]
  getitem_44["call_function\n<built-in function getitem>"]
  getitem_45["call_function\n<built-in function getitem>"]
  getitem_46["call_function\n<built-in function getitem>"]
  getitem_47["call_function\n<built-in function getitem>"]
  getitem_48["call_function\n<built-in function getitem>"]
  getitem_49["call_function\n<built-in function getitem>"]
  getitem_50["call_function\n<built-in function getitem>"]
  getitem_51["call_function\n<built-in function getitem>"]
  getitem_52["call_function\n<built-in function getitem>"]
  getitem_53["call_function\n<built-in function getitem>"]
  getitem_54["call_function\n<built-in function getitem>"]
  getitem_55["call_function\n<built-in function getitem>"]
  getitem_56["call_function\n<built-in function getitem>"]
  getitem_57["call_function\n<built-in function getitem>"]
  getitem_58["call_function\n<built-in function getitem>"]
  getitem_59["call_function\n<built-in function getitem>"]
  getitem_60["call_function\n<built-in function getitem>"]
  getitem_61["call_function\n<built-in function getitem>"]
  getitem_62["call_function\n<built-in function getitem>"]
  getitem_63["call_function\n<built-in function getitem>"]
  getitem_64["call_function\n<built-in function getitem>"]
  getitem_65["call_function\n<built-in function getitem>"]
  getitem_66["call_function\n<built-in function getitem>"]
  getitem_67["call_function\n<built-in function getitem>"]
  getitem_68["call_function\n<built-in function getitem>"]
  getitem_69["call_function\n<built-in function getitem>"]
  getitem_70["call_function\n<built-in function getitem>"]
  getitem_71["call_function\n<built-in function getitem>"]
  getitem_72["call_function\n<built-in function getitem>"]
  getitem_73["call_function\n<built-in function getitem>"]
  getitem_74["call_function\n<built-in function getitem>"]
  getitem_75["call_function\n<built-in function getitem>"]
  getitem_76["call_function\n<built-in function getitem>"]
  getitem_77["call_function\n<built-in function getitem>"]
  getitem_78["call_function\n<built-in function getitem>"]
  getitem_79["call_function\n<built-in function getitem>"]
  getitem_80["call_function\n<built-in function getitem>"]
  getitem_81["call_function\n<built-in function getitem>"]
  getitem_82["call_function\n<built-in function getitem>"]
  getitem_83["call_function\n<built-in function getitem>"]
  getitem_84["call_function\n<built-in function getitem>"]
  getitem_85["call_function\n<built-in function getitem>"]
  getitem_86["call_function\n<built-in function getitem>"]
  getitem_87["call_function\n<built-in function getitem>"]
  getitem_88["call_function\n<built-in function getitem>"]
  getitem_89["call_function\n<built-in function getitem>"]
  getitem_90["call_function\n<built-in function getitem>"]
  getitem_91["call_function\n<built-in function getitem>"]
  getitem_92["call_function\n<built-in function getitem>"]
  getitem_93["call_function\n<built-in function getitem>"]
  getitem_94["call_function\n<built-in function getitem>"]
  getitem_95["call_function\n<built-in function getitem>"]
  getitem_96["call_function\n<built-in function getitem>"]
  getitem_97["call_function\n<built-in function getitem>"]
  getitem_98["call_function\n<built-in function getitem>"]
  getitem_99["call_function\n<built-in function getitem>"]
  getitem_100["call_function\n<built-in function getitem>"]
  getitem_101["call_function\n<built-in function getitem>"]
  getitem_102["call_function\n<built-in function getitem>"]
  getitem_103["call_function\n<built-in function getitem>"]
  getitem_104["call_function\n<built-in function getitem>"]
  getitem_105["call_function\n<built-in function getitem>"]
  getitem_106["call_function\n<built-in function getitem>"]
  getitem_107["call_function\n<built-in function getitem>"]
  getitem_108["call_function\n<built-in function getitem>"]
  getitem_109["call_function\n<built-in function getitem>"]
  getitem_110["call_function\n<built-in function getitem>"]
  getitem_111["call_function\n<built-in function getitem>"]
  getitem_112["call_function\n<built-in function getitem>"]
  getitem_113["call_function\n<built-in function getitem>"]
  getitem_114["call_function\n<built-in function getitem>"]
  getitem_115["call_function\n<built-in function getitem>"]
  getitem_116["call_function\n<built-in function getitem>"]
  getitem_117["call_function\n<built-in function getitem>"]
  getitem_118["call_function\n<built-in function getitem>"]
  getitem_119["call_function\n<built-in function getitem>"]
  getitem_120["call_function\n<built-in function getitem>"]
  getitem_121["call_function\n<built-in function getitem>"]
  getitem_122["call_function\n<built-in function getitem>"]
  getitem_123["call_function\n<built-in function getitem>"]
  stack_12["call_function\n<built-in method stack of type object at 0x00007FF812C1EE90>"]
  stack_13["call_function\n<built-in method stack of type object at 0x00007FF812C1EE90>"]
  mul_29["call_function\n<built-in function mul>"]
  mean["call_method\nmean"]
  getattr_27["call_function\n<built-in function getattr>"]
  getitem_124["call_function\n<built-in function getitem>"]
  getattr_28["call_function\n<built-in function getattr>"]
  getitem_125["call_function\n<built-in function getitem>"]
  view_22["call_method\nview"]
  _tensor_constant0["get_attr\n_tensor_constant0"]
  mul_30["call_function\n<built-in function mul>"]
  sum_27["call_method\nsum"]
  tile_mask_counts["get_attr\ntile_mask_counts"]
  truediv_13["call_function\n<built-in function truediv>"]
  mul_31["call_function\n<built-in function mul>"]
  mean_1["call_method\nmean"]
  unsqueeze_20["call_method\nunsqueeze"]
  getattr_29["call_function\n<built-in function getattr>"]
  getitem_126["call_function\n<built-in function getitem>"]
  expand["call_method\nexpand"]
  model_condition_project["call_module\nmodel.condition_project"]
  cat["call_function\n<built-in method cat of type object at 0x00007FF812C1EE90>"]
  model_fusion_gate_0["call_module\nmodel.fusion_gate.0"]
  model_fusion_gate_1["call_module\nmodel.fusion_gate.1"]
  model_fusion_gate_2["call_module\nmodel.fusion_gate.2"]
  sigmoid["call_function\n<built-in method sigmoid of type object at 0x00007FF812C1EE90>"]
  mul_32["call_function\n<built-in function mul>"]
  sub["call_function\n<built-in function sub>"]
  mul_33["call_function\n<built-in function mul>"]
  add_21["call_function\n<built-in function add>"]
  mul_34["call_function\n<built-in function mul>"]
  add_22["call_function\n<built-in function add>"]
  model_reject_head["call_module\nmodel.reject_head"]
  squeeze["call_method\nsqueeze"]
  model_defect_head["call_module\nmodel.defect_head"]
  model_global_heatmap_head_0["call_module\nmodel.global_heatmap_head.0"]
  model_global_heatmap_head_1["call_module\nmodel.global_heatmap_head.1"]
  model_global_heatmap_head_2["call_module\nmodel.global_heatmap_head.2"]
  interpolate_7["call_function\n<function interpolate at 0x000001AD0D8E8790>"]
  mul_35["call_function\n<built-in function mul>"]
  mul_36["call_function\n<built-in function mul>"]
  add_23["call_function\n<built-in function add>"]
  sigmoid_1["call_function\n<built-in method sigmoid of type object at 0x00007FF812C1EE90>"]
  mul_37["call_function\n<built-in function mul>"]
  output["output\noutput"]
  station_id --> model_conditioner_station_embedding
  geometry_id --> model_conditioner_geometry_embedding
  model_conditioner_station_embedding --> add
  model_conditioner_geometry_embedding --> add
  add --> model_conditioner_proj_0
  model_conditioner_proj_0 --> model_conditioner_proj_1
  model_conditioner_proj_1 --> model_conditioner_proj_2
  model_conditioner_proj_2 --> model_conditioner_proj_3
  image --> model_stem_0_block_0
  model_stem_0_block_0 --> model_stem_0_block_1
  model_stem_0_block_1 --> model_stem_0_block_2
  model_stem_0_block_2 --> model_stem_1_block_0
  model_stem_1_block_0 --> model_stem_1_block_1
  model_stem_1_block_1 --> model_stem_1_block_2
  model_conditioner_proj_3 --> model_stem_affine_scale
  model_stem_affine_scale --> tanh
  tanh --> unsqueeze
  unsqueeze --> unsqueeze_1
  model_conditioner_proj_3 --> model_stem_affine_bias
  model_stem_affine_bias --> unsqueeze_2
  unsqueeze_2 --> unsqueeze_3
  unsqueeze_1 --> add_1
  model_stem_1_block_2 --> mul
  add_1 --> mul
  mul --> add_2
  unsqueeze_3 --> add_2
  add_2 --> model_stage1_proj
  model_stage1_proj --> model_stage1_0_depthwise
  model_stage1_0_depthwise --> permute
  model_stage1_0_depthwise --> getattr_1
  getattr_1 --> getitem
  permute --> layer_norm
  getitem --> layer_norm
  model_stage1_0_norm_weight --> layer_norm
  model_stage1_0_norm_bias --> layer_norm
  layer_norm --> permute_1
  permute_1 --> model_stage1_0_pointwise_0
  model_stage1_0_pointwise_0 --> model_stage1_0_pointwise_1
  model_stage1_0_pointwise_1 --> model_stage1_0_pointwise_2
  model_stage1_0_scale --> view
  view --> mul_1
  model_stage1_0_pointwise_2 --> mul_1
  model_stage1_proj --> add_3
  mul_1 --> add_3
  add_3 --> model_stage1_1_depthwise
  model_stage1_1_depthwise --> permute_2
  model_stage1_1_depthwise --> getattr_2
  getattr_2 --> getitem_1
  permute_2 --> layer_norm_1
  getitem_1 --> layer_norm_1
  model_stage1_1_norm_weight --> layer_norm_1
  model_stage1_1_norm_bias --> layer_norm_1
  layer_norm_1 --> permute_3
  permute_3 --> model_stage1_1_pointwise_0
  model_stage1_1_pointwise_0 --> model_stage1_1_pointwise_1
  model_stage1_1_pointwise_1 --> model_stage1_1_pointwise_2
  model_stage1_1_scale --> view_1
  view_1 --> mul_2
  model_stage1_1_pointwise_2 --> mul_2
  add_3 --> add_4
  mul_2 --> add_4
  model_conditioner_proj_3 --> model_stage1_affine_scale
  model_stage1_affine_scale --> tanh_1
  tanh_1 --> unsqueeze_4
  unsqueeze_4 --> unsqueeze_5
  model_conditioner_proj_3 --> model_stage1_affine_bias
  model_stage1_affine_bias --> unsqueeze_6
  unsqueeze_6 --> unsqueeze_7
  unsqueeze_5 --> add_5
  add_4 --> mul_3
  add_5 --> mul_3
  mul_3 --> add_6
  unsqueeze_7 --> add_6
  add_6 --> permute_4
  add_6 --> getattr_3
  getattr_3 --> getitem_2
  permute_4 --> layer_norm_2
  getitem_2 --> layer_norm_2
  model_stage2_down_block_0_weight --> layer_norm_2
  model_stage2_down_block_0_bias --> layer_norm_2
  layer_norm_2 --> permute_5
  permute_5 --> model_stage2_down_block_1
  model_stage2_down_block_1 --> model_stage2_0_depthwise
  model_stage2_0_depthwise --> permute_6
  model_stage2_0_depthwise --> getattr_4
  getattr_4 --> getitem_3
  permute_6 --> layer_norm_3
  getitem_3 --> layer_norm_3
  model_stage2_0_norm_weight --> layer_norm_3
  model_stage2_0_norm_bias --> layer_norm_3
  layer_norm_3 --> permute_7
  permute_7 --> model_stage2_0_pointwise_0
  model_stage2_0_pointwise_0 --> model_stage2_0_pointwise_1
  model_stage2_0_pointwise_1 --> model_stage2_0_pointwise_2
  model_stage2_0_scale --> view_2
  view_2 --> mul_4
  model_stage2_0_pointwise_2 --> mul_4
  model_stage2_down_block_1 --> add_7
  mul_4 --> add_7
  add_7 --> model_stage2_1_depthwise
  model_stage2_1_depthwise --> permute_8
  model_stage2_1_depthwise --> getattr_5
  getattr_5 --> getitem_4
  permute_8 --> layer_norm_4
  getitem_4 --> layer_norm_4
  model_stage2_1_norm_weight --> layer_norm_4
  model_stage2_1_norm_bias --> layer_norm_4
  layer_norm_4 --> permute_9
  permute_9 --> model_stage2_1_pointwise_0
  model_stage2_1_pointwise_0 --> model_stage2_1_pointwise_1
  model_stage2_1_pointwise_1 --> model_stage2_1_pointwise_2
  model_stage2_1_scale --> view_3
  view_3 --> mul_5
  model_stage2_1_pointwise_2 --> mul_5
  add_7 --> add_8
  mul_5 --> add_8
  model_conditioner_proj_3 --> model_stage2_affine_scale
  model_stage2_affine_scale --> tanh_2
  tanh_2 --> unsqueeze_8
  unsqueeze_8 --> unsqueeze_9
  model_conditioner_proj_3 --> model_stage2_affine_bias
  model_stage2_affine_bias --> unsqueeze_10
  unsqueeze_10 --> unsqueeze_11
  unsqueeze_9 --> add_9
  add_8 --> mul_6
  add_9 --> mul_6
  mul_6 --> add_10
  unsqueeze_11 --> add_10
  add_10 --> permute_10
  add_10 --> getattr_6
  getattr_6 --> getitem_5
  permute_10 --> layer_norm_5
  getitem_5 --> layer_norm_5
  model_stage3_down_block_0_weight --> layer_norm_5
  model_stage3_down_block_0_bias --> layer_norm_5
  layer_norm_5 --> permute_11
  permute_11 --> model_stage3_down_block_1
  model_stage3_down_block_1 --> model_stage3_0_depthwise
  model_stage3_0_depthwise --> permute_12
  model_stage3_0_depthwise --> getattr_7
  getattr_7 --> getitem_6
  permute_12 --> layer_norm_6
  getitem_6 --> layer_norm_6
  model_stage3_0_norm_weight --> layer_norm_6
  model_stage3_0_norm_bias --> layer_norm_6
  layer_norm_6 --> permute_13
  permute_13 --> model_stage3_0_pointwise_0
  model_stage3_0_pointwise_0 --> model_stage3_0_pointwise_1
  model_stage3_0_pointwise_1 --> model_stage3_0_pointwise_2
  model_stage3_0_scale --> view_4
  view_4 --> mul_7
  model_stage3_0_pointwise_2 --> mul_7
  model_stage3_down_block_1 --> add_11
  mul_7 --> add_11
  add_11 --> model_stage3_1_depthwise
  model_stage3_1_depthwise --> permute_14
  model_stage3_1_depthwise --> getattr_8
  getattr_8 --> getitem_7
  permute_14 --> layer_norm_7
  getitem_7 --> layer_norm_7
  model_stage3_1_norm_weight --> layer_norm_7
  model_stage3_1_norm_bias --> layer_norm_7
  layer_norm_7 --> permute_15
  permute_15 --> model_stage3_1_pointwise_0
  model_stage3_1_pointwise_0 --> model_stage3_1_pointwise_1
  model_stage3_1_pointwise_1 --> model_stage3_1_pointwise_2
  model_stage3_1_scale --> view_5
  view_5 --> mul_8
  model_stage3_1_pointwise_2 --> mul_8
  add_11 --> add_12
  mul_8 --> add_12
  add_12 --> model_stage3_2_depthwise
  model_stage3_2_depthwise --> permute_16
  model_stage3_2_depthwise --> getattr_9
  getattr_9 --> getitem_8
  permute_16 --> layer_norm_8
  getitem_8 --> layer_norm_8
  model_stage3_2_norm_weight --> layer_norm_8
  model_stage3_2_norm_bias --> layer_norm_8
  layer_norm_8 --> permute_17
  permute_17 --> model_stage3_2_pointwise_0
  model_stage3_2_pointwise_0 --> model_stage3_2_pointwise_1
  model_stage3_2_pointwise_1 --> model_stage3_2_pointwise_2
  model_stage3_2_scale --> view_6
  view_6 --> mul_9
  model_stage3_2_pointwise_2 --> mul_9
  add_12 --> add_13
  mul_9 --> add_13
  add_13 --> model_stage3_3_depthwise
  model_stage3_3_depthwise --> permute_18
  model_stage3_3_depthwise --> getattr_10
  getattr_10 --> getitem_9
  permute_18 --> layer_norm_9
  getitem_9 --> layer_norm_9
  model_stage3_3_norm_weight --> layer_norm_9
  model_stage3_3_norm_bias --> layer_norm_9
  layer_norm_9 --> permute_19
  permute_19 --> model_stage3_3_pointwise_0
  model_stage3_3_pointwise_0 --> model_stage3_3_pointwise_1
  model_stage3_3_pointwise_1 --> model_stage3_3_pointwise_2
  model_stage3_3_scale --> view_7
  view_7 --> mul_10
  model_stage3_3_pointwise_2 --> mul_10
  add_13 --> add_14
  mul_10 --> add_14
  model_conditioner_proj_3 --> model_stage3_affine_scale
  model_stage3_affine_scale --> tanh_3
  tanh_3 --> unsqueeze_12
  unsqueeze_12 --> unsqueeze_13
  model_conditioner_proj_3 --> model_stage3_affine_bias
  model_stage3_affine_bias --> unsqueeze_14
  unsqueeze_14 --> unsqueeze_15
  unsqueeze_13 --> add_15
  add_14 --> mul_11
  add_15 --> mul_11
  mul_11 --> add_16
  unsqueeze_15 --> add_16
  add_16 --> permute_20
  add_16 --> getattr_11
  getattr_11 --> getitem_10
  permute_20 --> layer_norm_10
  getitem_10 --> layer_norm_10
  model_stage4_down_block_0_weight --> layer_norm_10
  model_stage4_down_block_0_bias --> layer_norm_10
  layer_norm_10 --> permute_21
  permute_21 --> model_stage4_down_block_1
  model_stage4_down_block_1 --> model_stage4_0_depthwise
  model_stage4_0_depthwise --> permute_22
  model_stage4_0_depthwise --> getattr_12
  getattr_12 --> getitem_11
  permute_22 --> layer_norm_11
  getitem_11 --> layer_norm_11
  model_stage4_0_norm_weight --> layer_norm_11
  model_stage4_0_norm_bias --> layer_norm_11
  layer_norm_11 --> permute_23
  permute_23 --> model_stage4_0_pointwise_0
  model_stage4_0_pointwise_0 --> model_stage4_0_pointwise_1
  model_stage4_0_pointwise_1 --> model_stage4_0_pointwise_2
  model_stage4_0_scale --> view_8
  view_8 --> mul_12
  model_stage4_0_pointwise_2 --> mul_12
  model_stage4_down_block_1 --> add_17
  mul_12 --> add_17
  add_17 --> model_stage4_1_depthwise
  model_stage4_1_depthwise --> permute_24
  model_stage4_1_depthwise --> getattr_13
  getattr_13 --> getitem_12
  permute_24 --> layer_norm_12
  getitem_12 --> layer_norm_12
  model_stage4_1_norm_weight --> layer_norm_12
  model_stage4_1_norm_bias --> layer_norm_12
  layer_norm_12 --> permute_25
  permute_25 --> model_stage4_1_pointwise_0
  model_stage4_1_pointwise_0 --> model_stage4_1_pointwise_1
  model_stage4_1_pointwise_1 --> model_stage4_1_pointwise_2
  model_stage4_1_scale --> view_9
  view_9 --> mul_13
  model_stage4_1_pointwise_2 --> mul_13
  add_17 --> add_18
  mul_13 --> add_18
  model_conditioner_proj_3 --> model_stage4_affine_scale
  model_stage4_affine_scale --> tanh_4
  tanh_4 --> unsqueeze_16
  unsqueeze_16 --> unsqueeze_17
  model_conditioner_proj_3 --> model_stage4_affine_bias
  model_stage4_affine_bias --> unsqueeze_18
  unsqueeze_18 --> unsqueeze_19
  unsqueeze_17 --> add_19
  add_18 --> mul_14
  add_19 --> mul_14
  mul_14 --> add_20
  unsqueeze_19 --> add_20
  add_6 --> model_pyramid_laterals_0
  add_10 --> model_pyramid_laterals_1
  add_16 --> model_pyramid_laterals_2
  add_20 --> model_pyramid_laterals_3
  model_pyramid_laterals_2 --> getattr_14
  getattr_14 --> getitem_13
  model_pyramid_laterals_3 --> interpolate
  getitem_13 --> interpolate
  model_bifpn_0_td3_weights --> relu
  relu --> sum_1
  sum_1 --> clamp_min
  relu --> truediv
  clamp_min --> truediv
  model_pyramid_laterals_2 --> stack
  interpolate --> stack
  truediv --> view_10
  view_10 --> mul_15
  stack --> mul_15
  mul_15 --> sum_2
  sum_2 --> model_bifpn_0_td3_refine_0
  model_bifpn_0_td3_refine_0 --> model_bifpn_0_td3_refine_1
  model_bifpn_0_td3_refine_1 --> model_bifpn_0_td3_refine_2
  model_bifpn_0_td3_refine_2 --> model_bifpn_0_td3_refine_3
  model_pyramid_laterals_1 --> getattr_15
  getattr_15 --> getitem_14
  model_bifpn_0_td3_refine_3 --> interpolate_1
  getitem_14 --> interpolate_1
  model_bifpn_0_td2_weights --> relu_1
  relu_1 --> sum_3
  sum_3 --> clamp_min_1
  relu_1 --> truediv_1
  clamp_min_1 --> truediv_1
  model_pyramid_laterals_1 --> stack_1
  interpolate_1 --> stack_1
  truediv_1 --> view_11
  view_11 --> mul_16
  stack_1 --> mul_16
  mul_16 --> sum_4
  sum_4 --> model_bifpn_0_td2_refine_0
  model_bifpn_0_td2_refine_0 --> model_bifpn_0_td2_refine_1
  model_bifpn_0_td2_refine_1 --> model_bifpn_0_td2_refine_2
  model_bifpn_0_td2_refine_2 --> model_bifpn_0_td2_refine_3
  model_pyramid_laterals_0 --> getattr_16
  getattr_16 --> getitem_15
  model_bifpn_0_td2_refine_3 --> interpolate_2
  getitem_15 --> interpolate_2
  model_bifpn_0_td1_weights --> relu_2
  relu_2 --> sum_5
  sum_5 --> clamp_min_2
  relu_2 --> truediv_2
  clamp_min_2 --> truediv_2
  model_pyramid_laterals_0 --> stack_2
  interpolate_2 --> stack_2
  truediv_2 --> view_12
  view_12 --> mul_17
  stack_2 --> mul_17
  mul_17 --> sum_6
  sum_6 --> model_bifpn_0_td1_refine_0
  model_bifpn_0_td1_refine_0 --> model_bifpn_0_td1_refine_1
  model_bifpn_0_td1_refine_1 --> model_bifpn_0_td1_refine_2
  model_bifpn_0_td1_refine_2 --> model_bifpn_0_td1_refine_3
  model_pyramid_laterals_1 --> getattr_17
  getattr_17 --> getitem_16
  model_bifpn_0_td1_refine_3 --> adaptive_max_pool2d
  getitem_16 --> adaptive_max_pool2d
  model_bifpn_0_out2_weights --> relu_3
  relu_3 --> sum_7
  sum_7 --> clamp_min_3
  relu_3 --> truediv_3
  clamp_min_3 --> truediv_3
  model_pyramid_laterals_1 --> stack_3
  model_bifpn_0_td2_refine_3 --> stack_3
  adaptive_max_pool2d --> stack_3
  truediv_3 --> view_13
  view_13 --> mul_18
  stack_3 --> mul_18
  mul_18 --> sum_8
  sum_8 --> model_bifpn_0_out2_refine_0
  model_bifpn_0_out2_refine_0 --> model_bifpn_0_out2_refine_1
  model_bifpn_0_out2_refine_1 --> model_bifpn_0_out2_refine_2
  model_bifpn_0_out2_refine_2 --> model_bifpn_0_out2_refine_3
  model_pyramid_laterals_2 --> getattr_18
  getattr_18 --> getitem_17
  model_bifpn_0_out2_refine_3 --> adaptive_max_pool2d_1
  getitem_17 --> adaptive_max_pool2d_1
  model_bifpn_0_out3_weights --> relu_4
  relu_4 --> sum_9
  sum_9 --> clamp_min_4
  relu_4 --> truediv_4
  clamp_min_4 --> truediv_4
  model_pyramid_laterals_2 --> stack_4
  model_bifpn_0_td3_refine_3 --> stack_4
  adaptive_max_pool2d_1 --> stack_4
  truediv_4 --> view_14
  view_14 --> mul_19
  stack_4 --> mul_19
  mul_19 --> sum_10
  sum_10 --> model_bifpn_0_out3_refine_0
  model_bifpn_0_out3_refine_0 --> model_bifpn_0_out3_refine_1
  model_bifpn_0_out3_refine_1 --> model_bifpn_0_out3_refine_2
  model_bifpn_0_out3_refine_2 --> model_bifpn_0_out3_refine_3
  model_pyramid_laterals_3 --> getattr_19
  getattr_19 --> getitem_18
  model_bifpn_0_out3_refine_3 --> adaptive_max_pool2d_2
  getitem_18 --> adaptive_max_pool2d_2
  model_bifpn_0_out4_weights --> relu_5
  relu_5 --> sum_11
  sum_11 --> clamp_min_5
  relu_5 --> truediv_5
  clamp_min_5 --> truediv_5
  model_pyramid_laterals_3 --> stack_5
  adaptive_max_pool2d_2 --> stack_5
  truediv_5 --> view_15
  view_15 --> mul_20
  stack_5 --> mul_20
  mul_20 --> sum_12
  sum_12 --> model_bifpn_0_out4_refine_0
  model_bifpn_0_out4_refine_0 --> model_bifpn_0_out4_refine_1
  model_bifpn_0_out4_refine_1 --> model_bifpn_0_out4_refine_2
  model_bifpn_0_out4_refine_2 --> model_bifpn_0_out4_refine_3
  model_bifpn_0_out3_refine_3 --> getattr_20
  getattr_20 --> getitem_19
  model_bifpn_0_out4_refine_3 --> interpolate_3
  getitem_19 --> interpolate_3
  model_bifpn_1_td3_weights --> relu_6
  relu_6 --> sum_13
  sum_13 --> clamp_min_6
  relu_6 --> truediv_6
  clamp_min_6 --> truediv_6
  model_bifpn_0_out3_refine_3 --> stack_6
  interpolate_3 --> stack_6
  truediv_6 --> view_16
  view_16 --> mul_21
  stack_6 --> mul_21
  mul_21 --> sum_14
  sum_14 --> model_bifpn_1_td3_refine_0
  model_bifpn_1_td3_refine_0 --> model_bifpn_1_td3_refine_1
  model_bifpn_1_td3_refine_1 --> model_bifpn_1_td3_refine_2
  model_bifpn_1_td3_refine_2 --> model_bifpn_1_td3_refine_3
  model_bifpn_0_out2_refine_3 --> getattr_21
  getattr_21 --> getitem_20
  model_bifpn_1_td3_refine_3 --> interpolate_4
  getitem_20 --> interpolate_4
  model_bifpn_1_td2_weights --> relu_7
  relu_7 --> sum_15
  sum_15 --> clamp_min_7
  relu_7 --> truediv_7
  clamp_min_7 --> truediv_7
  model_bifpn_0_out2_refine_3 --> stack_7
  interpolate_4 --> stack_7
  truediv_7 --> view_17
  view_17 --> mul_22
  stack_7 --> mul_22
  mul_22 --> sum_16
  sum_16 --> model_bifpn_1_td2_refine_0
  model_bifpn_1_td2_refine_0 --> model_bifpn_1_td2_refine_1
  model_bifpn_1_td2_refine_1 --> model_bifpn_1_td2_refine_2
  model_bifpn_1_td2_refine_2 --> model_bifpn_1_td2_refine_3
  model_bifpn_0_td1_refine_3 --> getattr_22
  getattr_22 --> getitem_21
  model_bifpn_1_td2_refine_3 --> interpolate_5
  getitem_21 --> interpolate_5
  model_bifpn_1_td1_weights --> relu_8
  relu_8 --> sum_17
  sum_17 --> clamp_min_8
  relu_8 --> truediv_8
  clamp_min_8 --> truediv_8
  model_bifpn_0_td1_refine_3 --> stack_8
  interpolate_5 --> stack_8
  truediv_8 --> view_18
  view_18 --> mul_23
  stack_8 --> mul_23
  mul_23 --> sum_18
  sum_18 --> model_bifpn_1_td1_refine_0
  model_bifpn_1_td1_refine_0 --> model_bifpn_1_td1_refine_1
  model_bifpn_1_td1_refine_1 --> model_bifpn_1_td1_refine_2
  model_bifpn_1_td1_refine_2 --> model_bifpn_1_td1_refine_3
  model_bifpn_0_out2_refine_3 --> getattr_23
  getattr_23 --> getitem_22
  model_bifpn_1_td1_refine_3 --> adaptive_max_pool2d_3
  getitem_22 --> adaptive_max_pool2d_3
  model_bifpn_1_out2_weights --> relu_9
  relu_9 --> sum_19
  sum_19 --> clamp_min_9
  relu_9 --> truediv_9
  clamp_min_9 --> truediv_9
  model_bifpn_0_out2_refine_3 --> stack_9
  model_bifpn_1_td2_refine_3 --> stack_9
  adaptive_max_pool2d_3 --> stack_9
  truediv_9 --> view_19
  view_19 --> mul_24
  stack_9 --> mul_24
  mul_24 --> sum_20
  sum_20 --> model_bifpn_1_out2_refine_0
  model_bifpn_1_out2_refine_0 --> model_bifpn_1_out2_refine_1
  model_bifpn_1_out2_refine_1 --> model_bifpn_1_out2_refine_2
  model_bifpn_1_out2_refine_2 --> model_bifpn_1_out2_refine_3
  model_bifpn_0_out3_refine_3 --> getattr_24
  getattr_24 --> getitem_23
  model_bifpn_1_out2_refine_3 --> adaptive_max_pool2d_4
  getitem_23 --> adaptive_max_pool2d_4
  model_bifpn_1_out3_weights --> relu_10
  relu_10 --> sum_21
  sum_21 --> clamp_min_10
  relu_10 --> truediv_10
  clamp_min_10 --> truediv_10
  model_bifpn_0_out3_refine_3 --> stack_10
  model_bifpn_1_td3_refine_3 --> stack_10
  adaptive_max_pool2d_4 --> stack_10
  truediv_10 --> view_20
  view_20 --> mul_25
  stack_10 --> mul_25
  mul_25 --> sum_22
  sum_22 --> model_bifpn_1_out3_refine_0
  model_bifpn_1_out3_refine_0 --> model_bifpn_1_out3_refine_1
  model_bifpn_1_out3_refine_1 --> model_bifpn_1_out3_refine_2
  model_bifpn_1_out3_refine_2 --> model_bifpn_1_out3_refine_3
  model_bifpn_0_out4_refine_3 --> getattr_25
  getattr_25 --> getitem_24
  model_bifpn_1_out3_refine_3 --> adaptive_max_pool2d_5
  getitem_24 --> adaptive_max_pool2d_5
  model_bifpn_1_out4_weights --> relu_11
  relu_11 --> sum_23
  sum_23 --> clamp_min_11
  relu_11 --> truediv_11
  clamp_min_11 --> truediv_11
  model_bifpn_0_out4_refine_3 --> stack_11
  adaptive_max_pool2d_5 --> stack_11
  truediv_11 --> view_21
  view_21 --> mul_26
  stack_11 --> mul_26
  mul_26 --> sum_24
  sum_24 --> model_bifpn_1_out4_refine_0
  model_bifpn_1_out4_refine_0 --> model_bifpn_1_out4_refine_1
  model_bifpn_1_out4_refine_1 --> model_bifpn_1_out4_refine_2
  model_bifpn_1_out4_refine_2 --> model_bifpn_1_out4_refine_3
  model_bifpn_1_out4_refine_3 --> getattr_26
  getattr_26 --> getitem_25
  valid_mask --> interpolate_6
  getitem_25 --> interpolate_6
  model_bifpn_1_out4_refine_3 --> adaptive_avg_pool2d
  interpolate_6 --> adaptive_max_pool2d_6
  adaptive_avg_pool2d --> model_global_context_project
  model_global_context_project --> mul_27
  adaptive_max_pool2d_6 --> mul_27
  mul_27 --> mul_28
  adaptive_max_pool2d_6 --> mul_28
  adaptive_max_pool2d_6 --> sum_25
  sum_25 --> clamp_min_12
  mul_28 --> sum_26
  sum_26 --> truediv_12
  clamp_min_12 --> truediv_12
  truediv_12 --> model_global_project
  image --> getitem_26
  valid_mask --> getitem_27
  image --> getitem_28
  valid_mask --> getitem_29
  image --> getitem_30
  valid_mask --> getitem_31
  image --> getitem_32
  valid_mask --> getitem_33
  image --> getitem_34
  valid_mask --> getitem_35
  image --> getitem_36
  valid_mask --> getitem_37
  image --> getitem_38
  valid_mask --> getitem_39
  image --> getitem_40
  valid_mask --> getitem_41
  image --> getitem_42
  valid_mask --> getitem_43
  image --> getitem_44
  valid_mask --> getitem_45
  image --> getitem_46
  valid_mask --> getitem_47
  image --> getitem_48
  valid_mask --> getitem_49
  image --> getitem_50
  valid_mask --> getitem_51
  image --> getitem_52
  valid_mask --> getitem_53
  image --> getitem_54
  valid_mask --> getitem_55
  image --> getitem_56
  valid_mask --> getitem_57
  image --> getitem_58
  valid_mask --> getitem_59
  image --> getitem_60
  valid_mask --> getitem_61
  image --> getitem_62
  valid_mask --> getitem_63
  image --> getitem_64
  valid_mask --> getitem_65
  image --> getitem_66
  valid_mask --> getitem_67
  image --> getitem_68
  valid_mask --> getitem_69
  image --> getitem_70
  valid_mask --> getitem_71
  image --> getitem_72
  valid_mask --> getitem_73
  image --> getitem_74
  valid_mask --> getitem_75
  image --> getitem_76
  valid_mask --> getitem_77
  image --> getitem_78
  valid_mask --> getitem_79
  image --> getitem_80
  valid_mask --> getitem_81
  image --> getitem_82
  valid_mask --> getitem_83
  image --> getitem_84
  valid_mask --> getitem_85
  image --> getitem_86
  valid_mask --> getitem_87
  image --> getitem_88
  valid_mask --> getitem_89
  image --> getitem_90
  valid_mask --> getitem_91
  image --> getitem_92
  valid_mask --> getitem_93
  image --> getitem_94
  valid_mask --> getitem_95
  image --> getitem_96
  valid_mask --> getitem_97
  image --> getitem_98
  valid_mask --> getitem_99
  image --> getitem_100
  valid_mask --> getitem_101
  image --> getitem_102
  valid_mask --> getitem_103
  image --> getitem_104
  valid_mask --> getitem_105
  image --> getitem_106
  valid_mask --> getitem_107
  image --> getitem_108
  valid_mask --> getitem_109
  image --> getitem_110
  valid_mask --> getitem_111
  image --> getitem_112
  valid_mask --> getitem_113
  image --> getitem_114
  valid_mask --> getitem_115
  image --> getitem_116
  valid_mask --> getitem_117
  image --> getitem_118
  valid_mask --> getitem_119
  image --> getitem_120
  valid_mask --> getitem_121
  image --> getitem_122
  valid_mask --> getitem_123
  getitem_26 --> stack_12
  getitem_28 --> stack_12
  getitem_30 --> stack_12
  getitem_32 --> stack_12
  getitem_34 --> stack_12
  getitem_36 --> stack_12
  getitem_38 --> stack_12
  getitem_40 --> stack_12
  getitem_42 --> stack_12
  getitem_44 --> stack_12
  getitem_46 --> stack_12
  getitem_48 --> stack_12
  getitem_50 --> stack_12
  getitem_52 --> stack_12
  getitem_54 --> stack_12
  getitem_56 --> stack_12
  getitem_58 --> stack_12
  getitem_60 --> stack_12
  getitem_62 --> stack_12
  getitem_64 --> stack_12
  getitem_66 --> stack_12
  getitem_68 --> stack_12
  getitem_70 --> stack_12
  getitem_72 --> stack_12
  getitem_74 --> stack_12
  getitem_76 --> stack_12
  getitem_78 --> stack_12
  getitem_80 --> stack_12
  getitem_82 --> stack_12
  getitem_84 --> stack_12
  getitem_86 --> stack_12
  getitem_88 --> stack_12
  getitem_90 --> stack_12
  getitem_92 --> stack_12
  getitem_94 --> stack_12
  getitem_96 --> stack_12
  getitem_98 --> stack_12
  getitem_100 --> stack_12
  getitem_102 --> stack_12
  getitem_104 --> stack_12
  getitem_106 --> stack_12
  getitem_108 --> stack_12
  getitem_110 --> stack_12
  getitem_112 --> stack_12
  getitem_114 --> stack_12
  getitem_116 --> stack_12
  getitem_118 --> stack_12
  getitem_120 --> stack_12
  getitem_122 --> stack_12
  getitem_27 --> stack_13
  getitem_29 --> stack_13
  getitem_31 --> stack_13
  getitem_33 --> stack_13
  getitem_35 --> stack_13
  getitem_37 --> stack_13
  getitem_39 --> stack_13
  getitem_41 --> stack_13
  getitem_43 --> stack_13
  getitem_45 --> stack_13
  getitem_47 --> stack_13
  getitem_49 --> stack_13
  getitem_51 --> stack_13
  getitem_53 --> stack_13
  getitem_55 --> stack_13
  getitem_57 --> stack_13
  getitem_59 --> stack_13
  getitem_61 --> stack_13
  getitem_63 --> stack_13
  getitem_65 --> stack_13
  getitem_67 --> stack_13
  getitem_69 --> stack_13
  getitem_71 --> stack_13
  getitem_73 --> stack_13
  getitem_75 --> stack_13
  getitem_77 --> stack_13
  getitem_79 --> stack_13
  getitem_81 --> stack_13
  getitem_83 --> stack_13
  getitem_85 --> stack_13
  getitem_87 --> stack_13
  getitem_89 --> stack_13
  getitem_91 --> stack_13
  getitem_93 --> stack_13
  getitem_95 --> stack_13
  getitem_97 --> stack_13
  getitem_99 --> stack_13
  getitem_101 --> stack_13
  getitem_103 --> stack_13
  getitem_105 --> stack_13
  getitem_107 --> stack_13
  getitem_109 --> stack_13
  getitem_111 --> stack_13
  getitem_113 --> stack_13
  getitem_115 --> stack_13
  getitem_117 --> stack_13
  getitem_119 --> stack_13
  getitem_121 --> stack_13
  getitem_123 --> stack_13
  stack_12 --> mul_29
  stack_13 --> mul_29
  mul_29 --> mean
  mean --> getattr_27
  getattr_27 --> getitem_124
  mean --> getattr_28
  getattr_28 --> getitem_125
  mean --> view_22
  getitem_124 --> view_22
  getitem_125 --> view_22
  view_22 --> mul_30
  _tensor_constant0 --> mul_30
  mul_30 --> sum_27
  sum_27 --> truediv_13
  tile_mask_counts --> truediv_13
  truediv_13 --> mul_31
  valid_mask --> mul_31
  mul_31 --> mean_1
  mean_1 --> unsqueeze_20
  model_global_project --> getattr_29
  getattr_29 --> getitem_126
  unsqueeze_20 --> expand
  getitem_126 --> expand
  model_conditioner_proj_3 --> model_condition_project
  model_global_project --> cat
  expand --> cat
  model_condition_project --> cat
  cat --> model_fusion_gate_0
  model_fusion_gate_0 --> model_fusion_gate_1
  model_fusion_gate_1 --> model_fusion_gate_2
  model_fusion_gate_2 --> sigmoid
  sigmoid --> mul_32
  model_global_project --> mul_32
  sigmoid --> sub
  sub --> mul_33
  expand --> mul_33
  mul_32 --> add_21
  mul_33 --> add_21
  model_condition_project --> mul_34
  add_21 --> add_22
  mul_34 --> add_22
  add_22 --> model_reject_head
  model_reject_head --> squeeze
  add_22 --> model_defect_head
  model_bifpn_1_td1_refine_3 --> model_global_heatmap_head_0
  model_global_heatmap_head_0 --> model_global_heatmap_head_1
  model_global_heatmap_head_1 --> model_global_heatmap_head_2
  model_global_heatmap_head_2 --> interpolate_7
  interpolate_7 --> mul_35
  mul_31 --> mul_36
  mul_35 --> add_23
  mul_36 --> add_23
  add_23 --> sigmoid_1
  sigmoid_1 --> mul_37
  valid_mask --> mul_37
  squeeze --> output
  model_defect_head --> output
  mul_37 --> output
