"""Public package surface for the grayscale inspection framework."""

from .api import BaseModel, LiteModel
from .autofit import AutoFitPlan, AutoFitResult, resolve_autofit_plan, resume_autofit, run_autofit
from .calibration import CalibratedStationDecision, StationCalibration, StationCalibrator
from .cli import cli_main
from .data import (
    DistributedShardedSampler,
    GreyInspectionDataset,
    ManifestInspectionDataset,
    StationBalancedManifestSampler,
    build_dataset_manifest,
    build_dataset_ontology,
    build_dataset_splits,
    build_hf_dataset_manifest,
    build_hard_negative_subset,
    build_huggingface_dataset_manifest,
    collate_batch,
    group_samples_by_station,
    ingest_dataset_manifest,
    infer_station_configs,
    load_dataset_index,
    load_dataset_manifest,
    register_synthetic_recipe,
    validate_dataset_manifest,
)
from .engine import GreyModel
from .evaluation import (
    benchmark_manifest,
    build_calibration_report,
    evaluate_predictions,
    predict_dataset,
    predict_hierarchical_dataset,
)
from .explainability import build_audit_report, build_explanation_bundle
from .graphing import export_model_graph
from .hf_backends import (
    HuggingFaceClassificationAdapter,
    HuggingFaceDetectionAdapter,
    HuggingFaceSegmentationAdapter,
    build_huggingface_model_backend,
)
from .model_profiles import (
    MODEL_PROFILE_REGISTRY_DIRNAME,
    PROFILE_SCHEMA_VERSION,
    ModelProfile,
    delete_model_profile,
    ensure_default_model_profiles,
    list_model_profiles,
    load_model_profile,
    model_profile_path,
    model_profile_registry_dir,
    register_model_profile,
    save_model_profile,
)
from .prediction import run_batch_prediction_stage
from .preprocessing import PreparedImage, preprocess_image, preprocess_sample, stack_prepared_images
from .pretrain_registry import PretrainDatasetPreset, get_pretrain_dataset_preset, list_pretrain_dataset_presets
from .recovery import ensure_failure_bundle, write_failure_bundle
from .registry import compare_run_reports, latest_run_status, list_failure_records, list_run_statuses
from .runners import (
    StageResult,
    run_benchmark_stage,
    run_calibration_stage,
    run_domain_adaptation_stage,
    run_explain_audit_stage,
    run_explain_sample_stage,
    run_finetune_stage,
    run_prediction_stage,
    run_pretraining_stage,
    run_resume_stage,
)
from .synthetic import DefectInjection, inject_defect, inject_particle, inject_scratch, inject_streak
from .settings import (
    GREYMODEL_HOME_ENV,
    SETTINGS_FILENAME,
    GreyModelSettings,
    build_environment_report,
    default_greymodel_home,
    default_settings,
    ensure_settings,
    load_settings,
    save_settings,
    settings_path,
)
from .tiling import TileCoverage, TileGrid, build_tile_grid, compute_tile_coverage, verify_defect_coverage
from .tracking import (
    RunContext,
    create_run_context,
    load_run_status,
    log_epoch_metrics,
    log_metrics,
    log_step_metrics,
    snapshot_manifest,
    snapshot_run_config,
    update_run_status,
    write_summary,
)
from .training import TrainingBatch, TrainingConfig
from .types import (
    BoxAnnotation,
    DatasetIndex,
    DatasetRecord,
    FailureRecord,
    GeometryMode,
    HierarchicalPredictionRecord,
    ModelInput,
    ModelOutput,
    PredictionEvidence,
    PredictionRecord,
    RunStatusRecord,
    Sample,
    StationConfig,
    TensorBatch,
    TopTilePrediction,
)
from .ui import launch_streamlit_ui
from .version import __version__

__all__ = [
    "AutoFitPlan",
    "AutoFitResult",
    "BaseModel",
    "BoxAnnotation",
    "build_audit_report",
    "benchmark_manifest",
    "build_calibration_report",
    "build_dataset_manifest",
    "build_dataset_ontology",
    "build_dataset_splits",
    "build_explanation_bundle",
    "build_hf_dataset_manifest",
    "build_hard_negative_subset",
    "build_huggingface_dataset_manifest",
    "build_tile_grid",
    "CalibratedStationDecision",
    "cli_main",
    "collate_batch",
    "compare_run_reports",
    "compute_tile_coverage",
    "create_run_context",
    "DatasetIndex",
    "DatasetRecord",
    "DefectInjection",
    "DistributedShardedSampler",
    "ensure_failure_bundle",
    "evaluate_predictions",
    "export_model_graph",
    "FailureRecord",
    "GeometryMode",
    "GreyModel",
    "GreyModelSettings",
    "get_pretrain_dataset_preset",
    "GreyInspectionDataset",
    "HuggingFaceClassificationAdapter",
    "HuggingFaceDetectionAdapter",
    "HuggingFaceSegmentationAdapter",
    "group_samples_by_station",
    "HierarchicalPredictionRecord",
    "ingest_dataset_manifest",
    "infer_station_configs",
    "inject_defect",
    "inject_particle",
    "inject_scratch",
    "inject_streak",
    "latest_run_status",
    "launch_streamlit_ui",
    "list_failure_records",
    "list_pretrain_dataset_presets",
    "list_run_statuses",
    "LiteModel",
    "list_model_profiles",
    "load_dataset_index",
    "load_dataset_manifest",
    "load_model_profile",
    "load_run_status",
    "log_epoch_metrics",
    "log_metrics",
    "log_step_metrics",
    "ManifestInspectionDataset",
    "MODEL_PROFILE_REGISTRY_DIRNAME",
    "ModelInput",
    "ModelProfile",
    "ModelOutput",
    "PredictionEvidence",
    "PredictionRecord",
    "predict_dataset",
    "predict_hierarchical_dataset",
    "PreparedImage",
    "PretrainDatasetPreset",
    "PROFILE_SCHEMA_VERSION",
    "preprocess_image",
    "preprocess_sample",
    "register_model_profile",
    "register_synthetic_recipe",
    "resolve_autofit_plan",
    "resume_autofit",
    "RunContext",
    "run_autofit",
    "run_batch_prediction_stage",
    "run_benchmark_stage",
    "run_calibration_stage",
    "run_domain_adaptation_stage",
    "run_explain_audit_stage",
    "run_explain_sample_stage",
    "run_finetune_stage",
    "run_prediction_stage",
    "run_pretraining_stage",
    "run_resume_stage",
    "RunStatusRecord",
    "Sample",
    "snapshot_manifest",
    "snapshot_run_config",
    "stack_prepared_images",
    "StageResult",
    "StationBalancedManifestSampler",
    "StationCalibration",
    "StationCalibrator",
    "StationConfig",
    "TensorBatch",
    "TileCoverage",
    "TileGrid",
    "TopTilePrediction",
    "TrainingBatch",
    "TrainingConfig",
    "update_run_status",
    "validate_dataset_manifest",
    "verify_defect_coverage",
    "write_failure_bundle",
    "write_summary",
    "build_huggingface_model_backend",
    "build_environment_report",
    "default_greymodel_home",
    "default_settings",
    "delete_model_profile",
    "ensure_settings",
    "GREYMODEL_HOME_ENV",
    "ensure_default_model_profiles",
    "load_settings",
    "model_profile_path",
    "model_profile_registry_dir",
    "save_settings",
    "save_model_profile",
    "settings_path",
    "SETTINGS_FILENAME",
    "__version__",
]
